### ISSUE TITLE
Put FlowClient behind an interface

### ISSUE THREAD

**Issue by bfbachmann** [onflow/flow-go-sdk#129]
**Is your feature request related to a problem? Please describe.**
Right now the Flow client is just a struct, so mocking it in tests it quite difficult.

**Describe the solution you'd like**
Ideally the client exposes a concrete interface that we can mock out if we want to.

**Describe alternatives you've considered**
Developers who wish to mock out the client could also wrap it in _their own_ interface, but they really shouldn't have to do that imo. 

**Additional context**

**Comment by psiemens** [comment]
So you can almost do this already. `client.Client` uses the generated gRPC interface under the hood, and that interface is mocked in our own tests: https://github.com/onflow/flow-go-sdk/blob/master/client/client_test.go#L51-L52). You just need to call `client.NewFromRPCClient`.

But mocking at this level means you need to deal with the protobuf types directly, which I suppose isn't ideal for most end users. 🤔

I'll need to think about this a bit more. I don't want to return an interface directly from `client.NewClient` because that breaks the "[accept interfaces, return structs](https://mycodesmells.com/post/accept-interfaces-return-struct-in-go)" rule in Go, which I've grown to like. I also recently had a discussion about how it's better for the consuming package to define an interface that describes the values it will accept, rather than the other way around. Not trying to shoot this down at all, but I think it would be valid for your code to look something like this:

```go

type FlowClient interface {
  // define the functions you need
 GetLatestBlockHeader(ctx context.Context, isSealed bool, opts ...grpc.CallOption) (*flow.BlockHeader, error)
 SendTransaction(ctx context.Context, tx flow.Transaction, opts ...grpc.CallOption) error
}

type App struct {
  c flowClient
}

func NewApp(c FlowClient) app {
  return app{c: c}
}

// ...

import "github.com/onflow/flow-go-sdk/client"

c, _ := client.New("localhost:3569")
a := NewApp(c)

**Comment by Kay-Zee** [comment]
I want to add that having the client side of things as an interface is actually not that idiomatic for go. An example from the standard lib, with http.Client as the example: https://github.com/golang/go/issues/16047. 

The reasoning from that issue being that the intention of the package is NOT to have an interface that other people can implement, but rather to implement an interface with an API.

I'm not completely opposed to the idea of providing a "FlowClient" interface, but i do think more thought would be required to determine if it's appropriate, where in the package it lives, or if it should even be in this repo.

**Comment by bfbachmann** [comment]
@psiemens @Kay-Zee Thanks for the responses, they make a lot of sense. We used `NewFromRPCClient` to mock out the client in our tests, which I think suffices in most cases. I also agree that the `New` and `NewFromRPCClient` functions should return structs, not interfaces, and that it's probably cleaner for packages that depend on the Flow client to accept interfaces rather than the `FlowClient` struct. 

I think the only argument in favour of defining a client interface within the SDK would be that you save other people the work of having to do it themselves, but given what we're already said, defining this interface in the SDK would be putting dead code into the repo, since that interface wouldn't really be used by the SDK itself.

All that said, I actually think we should probably close this issue. If people defining their own interfaces or using the RPCClient to mock becomes a problem, we can come back to this.

**Comment by psiemens** [comment]
Sounds good, thanks @bfbachmann!
